title = "GitLeaks Configuration"

[extend]
useDefault = true

[[rules]]
description = "Direct API_KEY Assignment"
id = "direct-api-key-assignment"
regex = '''API_KEY\s*=\s*['"].*['"]'''
tags = ["key", "API"] 