title = "GitLeaks Configuration"

[extend]
useDefault = true

[[rules]]
description = "Direct OPENAI_API_KEY Assignment"
id = "direct-openai-api-key-assignment"
regex = '''OPENAI_API_KEY\s*=\s*['"].*['"]'''
tags = ["key", "API"] 