title = "GitLeaks Configuration"

[extend]
useDefault = true

[[rules]]
description = "AWS Access Key ID"
id = "aws-access-key-id"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z]{16,32}['\"]'''
tags = ["key", "AWS"]

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(api_key|apikey|secret|token)(.{0,20})?['\"][0-9a-zA-Z]{16,}['\"]'''
tags = ["key", "API"] 