apiVersion: v1
kind: Secret
metadata:
  name: gcp-artifact-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  # This will be replaced with the actual base64 encoded Docker config
  .dockerconfigjson: ${DOCKER_CONFIG_JSON} 