apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRegistries
metadata:
  name: must-use-approved-registry
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    registries:
      - "us-central1-docker.pkg.dev/cmpe58e-460900/devsecops-repo/"
      - "gcr.io/cmpe58e-460900/" 